package com.jakhar.rohit.viewpagertransformation

object Constant {
    const val TRANSFORMATION = "transformation"
    const val SLOW_TRANSFORMATION = "slow transformation"
    const val SIMPLE_TRANSFORMATION = "simple transformation"
    const val DEPTH_TRANSFORMATION = "depth transformation"
    const val ZOOM_OUT_TRANSFORMATION = "zoom transformation"
    const val CLOCK_SPIN_TRANSFORMATION = "clock_spin  transformation"
    const val ANTICLOCK_SPIN_TRANSFORMATION = "anticlock_spin transformation"
    const val FIDGET_SPINNER_TRANSFORMATION = "fidget_spinner transformation"
    const val VERTICAL_FLIP_TRANSFORMATION = "vertical_flip transformation"
    const val HORIZONTAL_FLIP_TRANSFORMATION = "horizontal_flip transformation"
    const val POP_TRANSFORMATION = "pop transformation"
    const val FADE_OUT_TRANSFORMATION = "fade_out transformation"
    const val CUBE_OUT_TRANSFORMATION = "cube_out transformation"
    const val CUBE_IN_TRANSFORMATION = "cube_in transformation"
    const val CUBE_OUT_SCALING_TRANSFORMATION = "cube_out_scaling transformation"
    const val CUBE_IN_SCALING_TRANSFORMATION = "cube_in_scaling transformation"
    const val CUBE_OUT_DEPTH_TRANSFORMATION = "cube_out_depth transformation"
    const val CUBE_IN_DEPTH_TRANSFORMATION = "cube_in_depth transformation"
    const val HINGE_TRANSFORMATION = "hinge transformation"
    const val GATE_TRANSFORMATION = "gate transformation"
    const val TOSS_TRANSFORMATION = "toss transformation"
    const val FAN_TRANSFORMATION = "fan transformation"
    const val SPINNER_TRANSFORMATION = "spinner transformation"
    const val VERTICAL_SHUT_TRANSFORMATION = "vertical_shut_transformation"
}